'use client'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { MetaMaskUIProvider } from "@metamask/sdk-react-ui"

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <MetaMaskUIProvider sdkOptions={{
        dappMetadata: {
          name: "Demo UI React App",
        }
      }}>
        <body className={inter.className}>{children}</body>
      </MetaMaskUIProvider>
    </html>
  )
}
